files:
  - source: /common/src/main/resources/assets/shulkerboxtooltip/lang/en_us.json
    translation: /common/src/main/resources/assets/shulkerboxtooltip/lang/%locale_with_underscore%.json
commit_message: "[ci skip]"
